name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0

  # For handle multilanguage and locale
  flutter_localizations:
    sdk: flutter

  # BLoC for state management
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.2

  # Freezed for creating unioin entities
  freezed_annotation: ^2.2.0

  # Json annotation for combine json methods to our models
  json_annotation: ^4.8.1

  # Service locators
  get_it: ^7.2.0
  injectable: ^2.3.0

  # For showing SVG files
  flutter_svg: ^2.0.7

  # For saving date into user local storage
  shared_preferences: ^2.2.1

  # For Highlighting texts
  highlight_text: ^1.7.0

  # For handling app typography styles
  google_fonts: ^6.1.0

  # For more and complex animations
  widget_and_text_animator: ^1.1.5

  # For check when a widget is visible on screen
  widget_visibility_detector: ^1.0.1

  # Good tool for handling tooltips
  just_the_tooltip: ^0.0.12

  # For handlign widget parallax in web with mouse
  mouse_parallax: ^1.1.0

  # For trigger when web window size changed
  window_manager: ^0.3.8

  # For create expandable widgets
  expandable: ^5.0.1

  # The brightest, hippest, coolest router for Flutter
  go_router: ^13.2.0

  # It allows listeners to subscribe for events and publishers to fire events
  event_bus: ^2.0.0

  # For restart the app when wanna change theme
  restart_app: ^1.2.1

  # Easy way to handle flags in your app
  country_flags: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Freezed for creating unioin entities
  freezed: ^2.3.4

  # Json serializable for combine json methods to our models
  json_serializable: ^6.1.5

  # Injectable generator for generate our Service locators codes
  injectable_generator: ^2.4.0

  # Build runner to let other packages like `Hive` or `Freezed` or `injectable_generator` generate theire data
  build_runner: ^2.1.7


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/shapes/
    - assets/icons/
